* ememoa/configure, 	* ememoa/config.h.in, 	* ememoa/Makefile.in, 	* ememoa/configure.ac, 	* ememoa/doc/Makefile.in, 	* ememoa/test/Makefile.in, 	* ememoa/include/Makefile.in, 	* ememoa/build-aux/Makefile.in, 	* ememoa/src/lib/ememoa/Makefile.in, 	* ememoa/src/lib/ememoa/ememoa_memory_base.c: Add some options for display allocation request and use of 64bits code.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -879,6 +879,10 @@ acx_pthread_config
 PTHREAD_CC
 PTHREAD_LIBS
 PTHREAD_CFLAGS
+USE64_TRUE
+USE64_FALSE
+ALLOC_REPORT_TRUE
+ALLOC_REPORT_FALSE
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1488,6 +1492,8 @@ Optional Features:
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-pthread       to disable pthread
+  --enable-use64          use 64Bits as often as possible
+  --enable-alloc-report   Report all call to malloc/free/realloc 64m version
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -5004,7 +5010,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5007 "configure"' > conftest.$ac_ext
+  echo '#line 5013 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7273,11 +7279,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7276: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7282: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7280: \$? = $ac_status" >&5
+   echo "$as_me:7286: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7563,11 +7569,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7566: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7572: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7570: \$? = $ac_status" >&5
+   echo "$as_me:7576: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7667,11 +7673,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7670: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7676: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7674: \$? = $ac_status" >&5
+   echo "$as_me:7680: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10029,7 +10035,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10032 "configure"
+#line 10038 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10129,7 +10135,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10132 "configure"
+#line 10138 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12549,11 +12555,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12552: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12558: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12556: \$? = $ac_status" >&5
+   echo "$as_me:12562: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12653,11 +12659,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12656: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12662: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12660: \$? = $ac_status" >&5
+   echo "$as_me:12666: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14230,11 +14236,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14233: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14239: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14237: \$? = $ac_status" >&5
+   echo "$as_me:14243: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14334,11 +14340,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14337: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14343: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14341: \$? = $ac_status" >&5
+   echo "$as_me:14347: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16534,11 +16540,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16537: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16543: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16541: \$? = $ac_status" >&5
+   echo "$as_me:16547: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16824,11 +16830,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16827: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16833: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16831: \$? = $ac_status" >&5
+   echo "$as_me:16837: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16928,11 +16934,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16931: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16937: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16935: \$? = $ac_status" >&5
+   echo "$as_me:16941: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20025,6 +20031,70 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 fi
 
+# More thing in one register :-)
+want_use64="no"
+{ echo "$as_me:$LINENO: checking whether to use 64bits often" >&5
+echo $ECHO_N "checking whether to use 64bits often... $ECHO_C" >&6; }
+# Check whether --enable-use64 was given.
+if test "${enable_use64+set}" = set; then
+  enableval=$enable_use64; want_use64=$enableval
+
+fi
+
+{ echo "$as_me:$LINENO: result: $want_use64" >&5
+echo "${ECHO_T}$want_use64" >&6; }
+
+
+
+if test "x$want_use64" = "xyes"; then
+  USE64_TRUE=
+  USE64_FALSE='#'
+else
+  USE64_TRUE='#'
+  USE64_FALSE=
+fi
+
+
+if test "x$want_use64" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define USE64 1
+_ACEOF
+
+fi
+
+# Display basic alloc request.
+want_basic_alloc_report="no"
+{ echo "$as_me:$LINENO: checking whether to display all call to basic 64m alloc" >&5
+echo $ECHO_N "checking whether to display all call to basic 64m alloc... $ECHO_C" >&6; }
+# Check whether --enable-alloc-report was given.
+if test "${enable_alloc_report+set}" = set; then
+  enableval=$enable_alloc_report; want_basic_alloc_report=$enableval
+
+fi
+
+{ echo "$as_me:$LINENO: result: $want_basic_alloc_report" >&5
+echo "${ECHO_T}$want_basic_alloc_report" >&6; }
+
+
+
+if test "x$want_basic_alloc_report" = "x$yes"; then
+  ALLOC_REPORT_TRUE=
+  ALLOC_REPORT_FALSE='#'
+else
+  ALLOC_REPORT_TRUE='#'
+  ALLOC_REPORT_FALSE=
+fi
+
+
+if test "x$want_basic_alloc_report" = "xyes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define ALLOC_REPORT 1
+_ACEOF
+
+fi
+
 # Configure files.
 ac_config_files="$ac_config_files include/Makefile src/lib/ememoa/Makefile doc/Makefile doc/doc.doxy test/Makefile"
 
@@ -20149,6 +20219,20 @@ if test -z "${am__fastdepCXX_TRUE}" && test -z "${am__fastdepCXX_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"am__fastdepCXX\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"am__fastdepCXX\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${USE64_TRUE}" && test -z "${USE64_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"USE64\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"USE64\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ALLOC_REPORT_TRUE}" && test -z "${ALLOC_REPORT_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ALLOC_REPORT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ALLOC_REPORT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -20841,11 +20925,15 @@ acx_pthread_config!$acx_pthread_config$ac_delim
 PTHREAD_CC!$PTHREAD_CC$ac_delim
 PTHREAD_LIBS!$PTHREAD_LIBS$ac_delim
 PTHREAD_CFLAGS!$PTHREAD_CFLAGS$ac_delim
+USE64_TRUE!$USE64_TRUE$ac_delim
+USE64_FALSE!$USE64_FALSE$ac_delim
+ALLOC_REPORT_TRUE!$ALLOC_REPORT_TRUE$ac_delim
+ALLOC_REPORT_FALSE!$ALLOC_REPORT_FALSE$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 16; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 20; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
